[18.944025040] 2019-09-04 14:16:19,385 - INFO - launcher: Starting sanity checks
[18.944025040] 2019-09-04 14:16:19,385 - INFO - launcher: Checking for Python 3.5+
[18.944025040] 2019-09-04 14:16:19,385 - INFO - launcher: Checking console encoding
[19.941568375] 2019-09-04 14:16:19,386 - INFO - launcher: Setting console encoding to UTF-8
[19.941568375] 2019-09-04 14:16:19,386 - INFO - launcher: Ensuring we're in the right environment
[20.938396454] 2019-09-04 14:16:19,387 - INFO - launcher: Adding local bins/ folder to path
[400.922536850] 2019-09-04 14:16:19,767 - INFO - launcher: Required checks passed.
[401.920557022] 2019-09-04 14:16:19,768 - INFO - launcher: Optional checks passed.
[401.920557022] 2019-09-04 14:16:19,768 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[0.8054630756378174] 2019-09-04 14:16:20,172 - WARNING - musicbot.config | In config.py::MainThread(32132), line 121 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[0.8054630756378174] 2019-09-04 14:16:20,172 - INFO - musicbot.config | In config.py::MainThread(32132), line 132 in run_checks: Using i18n: config/i18n/en.json
[0.8074815273284912] 2019-09-04 14:16:20,174 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 225 in _setup_logging: Set logging level to INFO
[0.8084790706634521] 2019-09-04 14:16:20,175 - DEBUG - musicbot.json | In json.py::MainThread(32132), line 8 in __init__: Init JSON obj with config/i18n/en.json
[0.8314290046691895] 2019-09-04 14:16:20,198 - INFO - musicbot.bot | In bot.py::MainThread(32132), line 90 in __init__: Starting MusicBot release-260819
[0.8323915004730225] 2019-09-04 14:16:20,198 - INFO - musicbot.bot | In bot.py::MainThread(32132), line 96 in __init__: Loaded autoplaylist with 2531 entries
[4.6199543476104736] 2019-09-04 14:16:23,986 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 951 in on_ready: Connection established, ready to go.
[4.6209077835083008] 2019-09-04 14:16:23,987 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 342 in _cache_app_info: Caching app info
[4.9341120719909668] 2019-09-04 14:16:24,300 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 773 in _scheck_ensure_env: Ensuring data folders exist
[4.9361045360565186] 2019-09-04 14:16:24,302 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 789 in _scheck_server_permissions: Checking server permissions
[4.9361045360565186] 2019-09-04 14:16:24,302 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 793 in _scheck_autoplaylist: Auditing autoplaylist
[4.9361045360565186] 2019-09-04 14:16:24,302 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 797 in _scheck_configs: Validating config
[4.9361045360565186] 2019-09-04 14:16:24,302 - DEBUG - musicbot.config | In config.py::MainThread(32132), line 236 in async_validate: Validating options...
[4.9371387958526611] 2019-09-04 14:16:24,303 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 800 in _scheck_configs: Validating permissions config
[4.9371387958526611] 2019-09-04 14:16:24,303 - DEBUG - musicbot.permissions | In permissions.py::MainThread(32132), line 94 in async_validate: Validating permissions...
[4.9371387958526611] 2019-09-04 14:16:24,303 - INFO - musicbot.bot | In bot.py::MainThread(32132), line 968 in on_ready: Connected: 618575052308480020/·¥ç·¥ús…™·¥Ñ#9195
[4.9390931129455566] 2019-09-04 14:16:24,305 - INFO - musicbot.bot | In bot.py::MainThread(32132), line 976 in on_ready: Owner:     461611806453137409/!          ‰∏ÇÔæëÔæâ„Ç∫ÔæëÔΩ≤ ‚ú®#0396

[4.9410903453826904] 2019-09-04 14:16:24,307 - INFO - musicbot.bot | In bot.py::MainThread(32132), line 979 in on_ready: Guild List:
[4.9420881271362305] 2019-09-04 14:16:24,308 - INFO - musicbot.bot | In bot.py::MainThread(32132), line 983 in on_ready:  - s…¥·¥ã  ú…™·¥Ö·¥á  ô·¥Ä·¥Ñ·¥ã-·¥ú·¥ò ùü∏
[4.9440796375274658] 2019-09-04 14:16:24,310 - INFO - musicbot.bot | In bot.py::MainThread(32132), line 1039 in on_ready: Not bound to any text channels
[4.9451212882995605] 2019-09-04 14:16:24,311 - INFO - musicbot.bot | In bot.py::MainThread(32132), line 1065 in on_ready: Not autojoining any voice channels
[18.5144438743591309] 2019-09-04 14:16:37,881 - INFO - musicbot.bot | In bot.py::MainThread(32132), line 2706 in on_message: 461611806453137409/!          ‰∏ÇÔæëÔæâ„Ç∫ÔæëÔΩ≤ ‚ú®#0396: !summon
[19.6449804306030273] 2019-09-04 14:16:39,011 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 733 in deserialize_queue: Deserializing queue for 595553731119153163
[19.7581496238708496] 2019-09-04 14:16:39,124 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 425 in get_player: Created player via deserialization for guild 595553731119153163 with 1 entries
[19.7591471672058105] 2019-09-04 14:16:39,125 - INFO - musicbot.bot | In bot.py::MainThread(32132), line 1935 in cmd_summon: Joining s…¥·¥ã  ú…™·¥Ö·¥á  ô·¥Ä·¥Ñ·¥ã-·¥ú·¥ò ùü∏/Music
[19.7611417770385742] 2019-09-04 14:16:39,127 - DEBUG - musicbot.entry | In entry.py::MainThread(32132), line 56 in get_ready_future: Created future for audio_cache\youtube-jjUwrr3YsNA-Best_Music_Mix_No_Copyright_Music_Gaming_Music_x_Trap_House_Dubstep.webm
[19.7611417770385742] 2019-09-04 14:16:39,127 - FFMPEG - musicbot.player | In player.py::MainThread(32132), line 293 in _play: Creating player with options: -nostdin -vn audio_cache\youtube-jjUwrr3YsNA-Best_Music_Mix_No_Copyright_Music_Gaming_Music_x_Trap_House_Dubstep.webm
[19.7621388435363770] 2019-09-04 14:16:39,128 - DEBUG - musicbot.player | In player.py::MainThread(32132), line 306 in _play: Playing <musicbot.player.SourcePlaybackCounter object at 0x04C4AE30> using <discord.voice_client.VoiceClient object at 0x05347D50>
[19.7631363868713379] 2019-09-04 14:16:39,129 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 460 in on_player_play: Running on_player_play
[19.7631363868713379] 2019-09-04 14:16:39,129 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 709 in serialize_queue: Serializing queue for 595553731119153163
[528.1238076686859131] 2019-09-04 14:25:07,490 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 3004 in on_guild_available: Guild "s…¥·¥ã  ú…™·¥Ö·¥á  ô·¥Ä·¥Ñ·¥ã-·¥ú·¥ò ùü∏" has become available.
[530.1255443096160889] 2019-09-04 14:25:09,492 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 951 in on_ready: Connection established, ready to go.
[530.1255443096160889] 2019-09-04 14:25:09,492 - DEBUG - musicbot.bot | In bot.py::MainThread(32132), line 956 in on_ready: Received additional READY event, may have failed to resume
